ekf_filter_node:
  ros__parameters:
    frequency: 30.0

    two_d_mode: true  # Run EKF in 2D mode (no Z)
    use_odometry: false  # No `/odom` data available

    # Reference frames
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    # IMU as the only sensor
    imu0: /robot_control/imu_raw
    imu0_config: [false, false, false,  # X, Y, Z Position (Disabled)
                  false, false, false,   # Roll, Pitch (Disabled), Yaw (Enabled)
                  false, false, false,  # Velocity (Disabled)
                  true, true, true,   # Angular Velocity X/Y (Disabled), Z (Enabled)
                  true, true, true]    # Acceleration X/Y (Enabled), Z (Disabled)

    imu0_bias_estimation: true
    imu0_remove_gravity: true
    imu0_differential: true

    publish_tf: true
    print_diagnostics: true
